
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class home extends javax.swing.JFrame {
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doctor_ = new javax.swing.JButton();
        nurse_ = new javax.swing.JButton();
        admin_ = new javax.swing.JButton();
        pharmacy_ = new javax.swing.JButton();
        logout_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 760));

        doctor_.setBackground(new java.awt.Color(0, 102, 204));
        doctor_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        doctor_.setForeground(new java.awt.Color(255, 255, 255));
        doctor_.setText("doctor");
        doctor_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        doctor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor_ActionPerformed(evt);
            }
        });
        jPanel1.add(doctor_, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 210, 50));

        nurse_.setBackground(new java.awt.Color(0, 102, 204));
        nurse_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        nurse_.setForeground(new java.awt.Color(255, 255, 255));
        nurse_.setText("nurse");
        nurse_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nurse_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurse_ActionPerformed(evt);
            }
        });
        jPanel1.add(nurse_, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 230, 50));

        admin_.setBackground(new java.awt.Color(0, 102, 204));
        admin_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        admin_.setForeground(new java.awt.Color(255, 255, 255));
        admin_.setText("admin");
        admin_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admin_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_ActionPerformed(evt);
            }
        });
        jPanel1.add(admin_, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 220, 50));

        pharmacy_.setBackground(new java.awt.Color(0, 102, 204));
        pharmacy_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        pharmacy_.setForeground(new java.awt.Color(255, 255, 255));
        pharmacy_.setText("pharmacy");
        pharmacy_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pharmacy_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacy_ActionPerformed(evt);
            }
        });
        jPanel1.add(pharmacy_, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 230, 50));

        logout_.setBackground(new java.awt.Color(0, 102, 204));
        logout_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        logout_.setForeground(new java.awt.Color(255, 255, 255));
        logout_.setText("logout");
        logout_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_ActionPerformed(evt);
            }
        });
        jPanel1.add(logout_, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 700, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_ActionPerformed
        // TODO add your handling code here:
        
            setVisible(false);
            new welcome().setVisible(true);

    }//GEN-LAST:event_logout_ActionPerformed

    private void admin_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_ActionPerformed

    private void doctor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_doctor_ActionPerformed

    private void nurse_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurse_ActionPerformed
        setVisible(false);
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_nurse_ActionPerformed

    private void pharmacy_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacy_ActionPerformed
        setVisible(false);
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_pharmacy_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_;
    private javax.swing.JButton doctor_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_;
    private javax.swing.JButton nurse_;
    private javax.swing.JButton pharmacy_;
    // End of variables declaration//GEN-END:variables
}
