
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        userame = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        close_ = new javax.swing.JButton();
        login_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 340, 60));

        userame.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        userame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(userame, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 340, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LL.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 790));

        close_.setBackground(new java.awt.Color(51, 102, 255));
        close_.setFont(new java.awt.Font("Artifakt Element Black", 1, 18)); // NOI18N
        close_.setForeground(new java.awt.Color(255, 255, 255));
        close_.setText("close");
        close_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_ActionPerformed(evt);
            }
        });
        jPanel1.add(close_, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 690, 220, 70));

        login_.setBackground(new java.awt.Color(0, 102, 255));
        login_.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 18)); // NOI18N
        login_.setForeground(new java.awt.Color(255, 255, 255));
        login_.setText("login");
        login_.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_ActionPerformed(evt);
            }
        });
        jPanel1.add(login_, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, 210, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_ActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"Do u really want to go back","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            setVisible(false);
            new home().setVisible(true);
        }
    }//GEN-LAST:event_close_ActionPerformed

    private void login_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_ActionPerformed
        //admin
        if (userame.getText().equals("maryam")&& password.getText().equals("0000")){
            setVisible(false);
            new admin().setVisible(true);
        }
        //doctor
        else if(password.getText().equals("1111")&& userame.getText().equals("aaila")){
            setVisible(false);
            new patient().setVisible(true);
        } 
        //nurse
        else if(password.getText().equals("2222")&& userame.getText().equals("zainab")){
            setVisible(false);
            new nurseview().setVisible(true);
        } 
        //pharmacy
        else if(password.getText().equals("3333")&& userame.getText().equals("izzah")){
            setVisible(false);
            new pharmacy().setVisible(true);
        } 
        else
        {
            JOptionPane.showMessageDialog(null, "Incorrect username or passward ;(");
        }
    }//GEN-LAST:event_login_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userame;
    // End of variables declaration//GEN-END:variables
}
