
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zainab
 */
public class updatemed extends javax.swing.JFrame {

    /**
     * Creates new form updatemed
     */
    Connection conn = null;
    public updatemed() {
        super("UpdateMed");
        initComponents();
        conn = databaseconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        medid = new javax.swing.JTextField();
        medname = new javax.swing.JTextField();
        medprice = new javax.swing.JTextField();
        medquantity = new javax.swing.JTextField();
        medmfgdate = new javax.swing.JTextField();
        medexpdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBackground(new java.awt.Color(10, 153, 153));
        search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, 30));

        medid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medidActionPerformed(evt);
            }
        });
        jPanel1.add(medid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 260, 30));

        medname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mednameActionPerformed(evt);
            }
        });
        jPanel1.add(medname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 260, 30));
        jPanel1.add(medprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 260, 30));
        jPanel1.add(medquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 260, 30));
        jPanel1.add(medmfgdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 260, 30));
        jPanel1.add(medexpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 260, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updatemed.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        delete.setText("jButton1");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, 180, 40));

        update.setText("jButton1");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 180, 40));

        back.setText("jButton1");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medidActionPerformed

    private void mednameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mednameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mednameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        pharmacy obj = new pharmacy();
        obj.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            Statement stmt = conn.createStatement();
            int id = Integer.parseInt(medid.getText());
            // delete the data from pharmacy
            String sql = "DELETE FROM pharmacy WHERE medid = '"+id+"'";
            stmt.executeUpdate(sql);
            

            JOptionPane.showMessageDialog(null,"Data is sucessfully deleted.");
            medid.setText("");
            medname.setText("");
            medprice.setText("");
            medquantity.setText("");
            medmfgdate.setText("");
            medexpdate.setText("");

        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            Statement stmt = conn.createStatement();
    
            
            int id = Integer.parseInt(medid.getText());
            String name = medname.getText();
            int price = Integer.parseInt(medprice.getText());
            int quantity = Integer.parseInt(medquantity.getText());
            String mfgdate = medmfgdate.getText();
            String expdate = medexpdate.getText();

            // update the data in pharmacy
            String sql = "UPDATE pharmacy SET medname = '"+name+"', medprice= '"+price+"', medquantity = '"+quantity+"',  medmfgdate = '"+mfgdate+"', medexpdate = '"+expdate+"'";
            stmt.executeUpdate(sql);
           
            

            JOptionPane.showMessageDialog(null,"Data is sucessfully updated.");
            medid.setText("");
            medname.setText("");
            medprice.setText("");
            medquantity.setText("");
            medmfgdate.setText("");
            medexpdate.setText("");
            

        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
            Statement stmt = conn.createStatement();
            int id = Integer.parseInt(medid.getText());
            String sql = "SELECT * FROM pharmacy WHERE medid = '"+id+"'";
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                medname.setText(rs.getString("medname"));
                medprice.setText(rs.getString("medprice"));
                medquantity.setText(rs.getString("medquantity"));
                medmfgdate.setText(rs.getString("medmfgdate"));
                medexpdate.setText(rs.getString("medexpdate"));
            }
            else{
                JOptionPane.showMessageDialog(null,"Record Not Found");
            }

        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatemed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatemed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatemed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatemed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatemed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField medexpdate;
    private javax.swing.JTextField medid;
    private javax.swing.JTextField medmfgdate;
    private javax.swing.JTextField medname;
    private javax.swing.JTextField medprice;
    private javax.swing.JTextField medquantity;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
